### ISSUE TITLE
Loss权重

### ISSUE THREAD

**Issue by sky-fly97** [InchSoup/HWCC2020_RS_segmentation#1]
`criterion = nn.CrossEntropyLoss(weight=torch.FloatTensor([3, 1]), reduction='mean').to(device)`
你好，请问这个loss权重是如何选取的呢?

**Comment by InchSoup** [comment]
根据经验设置，没有过多去调优

**Comment by InchSoup** [comment]
> `criterion = nn.CrossEntropyLoss(weight=torch.FloatTensor([3, 1]), reduction='mean').to(device)`
> 你好，请问这个loss权重是如何选取的呢?

根据经验设置，没有过多去调优

**Comment by sky-fly97** [comment]
> > `criterion = nn.CrossEntropyLoss(weight=torch.FloatTensor([3, 1]), reduction='mean').to(device)`
> > 你好，请问这个loss权重是如何选取的呢?
> 
> 根据经验设置，没有过多去调优

emm,  torch.FloatTensor([3, 1]，这不是随机的数嘛

**Comment by sky-fly97** [comment]
> > `criterion = nn.CrossEntropyLoss(weight=torch.FloatTensor([3, 1]), reduction='mean').to(device)`
> > 你好，请问这个loss权重是如何选取的呢?
> 
> 根据经验设置，没有过多去调优

好滴感谢~ 请问loss权重这一项的影响大吗

**Comment by InchSoup** [comment]
> > > `criterion = nn.CrossEntropyLoss(weight=torch.FloatTensor([3, 1]), reduction='mean').to(device)`
> > > 你好，请问这个loss权重是如何选取的呢?
> > 
> > 
> > 根据经验设置，没有过多去调优
> 
> 好滴感谢~ 请问loss权重这一项的影响大吗

蛮大的，在baseline上面测试能涨一个点
